<a href="https://colab.research.google.com/github/bvidru/BVB_project/blob/main/BVB_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import libraries

In [165]:
# Import libraries
import pandas as pd
import glob
import numpy as np
from collections import defaultdict
from datetime import datetime, timedelta
#Load the dataset by mounting drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Extract files into DataFrames

In [166]:
# Folder Path
path = r"drive/MyDrive/Colab Notebooks/BVB_project/BVB_raport_zilnic"

In [167]:
# extract all files used for analysis

all_files = glob.glob(path + "/*.xls")

In [168]:
# check the number of files used for our analysis

len(all_files)

146

In [169]:
# create a list of dictionaries with all files as dataframes
allfiles_list = []

for filename in all_files:
  df = pd.read_excel(filename, sheet_name = None, index_col=None, header=0)
  allfiles_list.append(df)

In [170]:
type(allfiles_list)

list

In [171]:
#allfiles_list[0:1]

### Create DataFrames for every each sheet used for analysis

In [172]:
# create dataframes for every sheet from all files used for analysis

def concatenate_dataframes_with_same_key(dict_list, key):
    """
    Concatenate DataFrames with the same key from a list of dictionaries
    and return a new DataFrame.

    Args:
    dict_list (list): List of dictionaries where values are DataFrames.
    key (str): The key to identify DataFrames with the same key.

    Returns:
    pd.DataFrame: A concatenated DataFrame.
    """
    # Create a dictionary to group DataFrames by their key
    grouped_dataframes = {}
    for d in dict_list:
        if key in d and isinstance(d[key], pd.DataFrame):
            if key not in grouped_dataframes:
                grouped_dataframes[key] = []
            grouped_dataframes[key].append(d[key])

    # Concatenate DataFrames within each group
    concatenated_dataframes = []
    for df_list in grouped_dataframes.values():
        if len(df_list) > 1:
            concatenated_df = pd.concat(df_list, ignore_index=True)
            concatenated_dataframes.append(concatenated_df)

    # Concatenate the DataFrames from all groups into a single DataFrame
    result_df = pd.concat(concatenated_dataframes, ignore_index=True)

    return result_df

In [173]:
# extract all summary report in a dataframe - df_summary

df_summary = concatenate_dataframes_with_same_key(allfiles_list, 'Sumar - Summary')

In [174]:
# quick view of df_summary

df_summary.sample(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
2602,Actiuni / Shares,0,0,0,0,0,NaN,BET-BK USD,1417.23,-3.33,-0.234415,NaN,NaN
4933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BET-FI LEI,49308.7,606.22,1.244742,49308.7,48702.48
6102,PRODUSE STRUCTURATE / STRUCTURED,NaN,NaN,NaN,NaN,NaN,NaN,BET-TR EUR,24104.72,-388.73,-1.587077,NaN,NaN
2050,Actiuni / Shares,0,0,0,0,0,NaN,BET-BK USD,1473.81,3.97,0.270097,NaN,NaN
6128,"Capitalizare SIF,FP / Capitalization SIF,FP",16879.644236,3741.885222,3410.718172,NaN,NaN,NaN,BETPlus LEI,1954.47,1.66,0.085006,1955.25,1947.89

In [175]:
# extract all equities report in a dataframe - df_equities

df_equities = concatenate_dataframes_with_same_key(allfiles_list, 'Titluri Capital - Equities')

In [176]:
# quick view of df_equities

df_equities.sample(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
24151,NaN,NaN,NaN,Regular,NaN,0.107,4.9,0.1045,0.107,0.104,0.1045,56000,5847,9,NaN,NaN
8573,NaN,EMISE DE ENTITATI DIN ROMANIA / DOMESTIC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16008,NaN,TITLURI DE CAPITAL / EQUITIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18700,NaN,MCAB,ROMCAB SA,TOTAL,0.1,0.12,0.84,0.119,0.12,0.115,0.1171,61026,7149.648,17,0.23,0.0974

In [177]:
# extract all unlisted shares report in a dataframe - df_unlisted_shares

df_unlisted_shares = concatenate_dataframes_with_same_key(allfiles_list, 'Necotate - Unlisted shares')

In [178]:
# quick view of df_unlisted_shares

df_unlisted_shares.sample(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
1113,Symbol,Company name,Face value,Close,Change %,Open,High,Low,Average price,Volume,Turnover value,Trades
821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
767,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,ACTIUNI NECOTATE TRANZACTIONATE PRIN SISTEMUL ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [179]:
# extract all bonds report in a dataframe - df_bonds

df_bonds = concatenate_dataframes_with_same_key(allfiles_list, 'Obligatiuni - Bonds')

In [180]:
# quick view of df_bonds

df_bonds.sample(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
13012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4628,R2403A,NaN,REGT,762,74537.98,3,95.3289,95.5,95.5,95.3,95.3,-0.31
5441,NaN,Pretul de inchidere din piata principala a rez...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28698,R2404B,NaN,TOTAL,11170,1153240.2,19,100.0444,100.4001,100.7495,100,100.7495,0.35
21619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [181]:
# extract all funds report in a dataframe - df_funds

df_funds = concatenate_dataframes_with_same_key(allfiles_list, 'OPC-Funds')

In [182]:
# quick view of df_funds

df_funds.sample(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
3749,NaN,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,TOTAL,5,20,0.23,20.03,20.07,19.94,19.9869,17419,348152.011,357,20.4,15.86
505,NaN,NaN,TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13769,241779.544,206,NaN,NaN
2532,NaN,Simbol / Symbol,Denumire societate / Company name,Sectiune piata / Market,VN / Face value,Inch./ Close,Var / Change (%),Desc. / Open,Max. / High,Min. / Low,Pr.med. / Avg.,Nr.actiuni / Volume,Val. totala / Turnover,Nr.trz. / No. of trades,52 Max / 52 High,52 Min / 52 Min
3343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2053,NaN,PTENGETF,FONDUL DESCHIS DE INVESTITII ETF ENERGIE PATRI...,TOTAL,5,5.174,0.82,5.176,5.176,5.125,5.1652,4483,23156.011,34,5.327,4.903

In [183]:
# extract all futures report in a dataframe - df_futures

df_futures = concatenate_dataframes_with_same_key(allfiles_list, 'Futures')

In [184]:
# quick view of df_futures

df_futures.sample(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
3818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,NaN,NaN,NaN,Desc./ Open,Max. / High,Min. / Low,Inch./ Close,Pr.med. / Avg.,Pret zilnic de decontare / Daily Settle,Net,...,Max / High,Min. / Low,NaN,NaN,Net,%,NaN,Net,%,NaN
777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4663,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [185]:
# extract all structured report in a dataframe - df_structured

df_structured = concatenate_dataframes_with_same_key(allfiles_list, 'Structured')

In [186]:
# quick view of df_structured

df_structured.sample(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
5789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7767,NaN,EBSNGTL11,ROMGAZ TURBO LONG 10/28.10/30.10,Regular STR,122.88,5.99,122.88,122.88,122.88,122.88,2,245.76,1,232.43,102.97
9829,NaN,EBEUSDTS24,EUR/USD TURBO SHORT 10/1.305/1.3,Regular STR,6.06,1.34,6.06,6.06,6.06,6.06,100,606,1,14.98,5.98
9781,NaN,BKAURTL15,BRK Aur Turbo Long 1500,Regular STR,21.9,-1.17,21.9,21.9,21.9,21.9,33,722.7,1,24.5,7.2
9244,NaN,EBTLVTL18,BANCA TRANSILVA. TURBO LONG 10/1.67/1.75,Regular STR,8.37,-3.79,8.37,8.37,8.37,8.37,10,83.7,1,9.81,4.33

In [187]:
# extract all other instruments report in a dataframe - df_other_inst

df_other_inst = concatenate_dataframes_with_same_key(allfiles_list, 'Alte int. - Other int.')

In [188]:
# quick view df_other_inst

df_other_inst.sample(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
1721,NaN,Drepturi / Rights,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,NaN,CATEGORIA B / B CATEGORY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Cleaning row data

## DF Summary

In [189]:
# view summary info of df_summary

df_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6716 entries, 0 to 6715
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   4088 non-null   object
 1   Unnamed: 1   3066 non-null   object
 2   Unnamed: 2   3066 non-null   object
 3   Unnamed: 3   2920 non-null   object
 4   Unnamed: 4   2336 non-null   object
 5   Unnamed: 5   2336 non-null   object
 6   Unnamed: 6   0 non-null      float64
 7   Unnamed: 7   4672 non-null   object
 8   Unnamed: 8   4672 non-null   object
 9   Unnamed: 9   4672 non-null   object
 10  Unnamed: 10  4672 non-null   object
 11  Unnamed: 11  1752 non-null   object
 12  Unnamed: 12  1752 non-null   object
dtypes: float64(1), object(12)
memory usage: 682.2+ KB

In [190]:
# view shape of df_summary

df_summary.shape

(6716, 13)

In [191]:
# drop all rows with null obs on df

df_summar = df_summary.dropna(how = 'all')
df_summar.shape

(5548, 13)

In [192]:
# create a function to check if dataframe has got columns only with null observations

def only_nan(df):

  result = {}

  for column in df.columns:
    only_null_col = df[column].isna().all()
    result[column] = only_null_col

  return result

In [193]:
# check if there is any null column on df_summar

summary = only_nan(df_summar)
summary

{'Unnamed: 0': False,
 'Unnamed: 1': False,
 'Unnamed: 2': False,
 'Unnamed: 3': False,
 'Unnamed: 4': False,
 'Unnamed: 5': False,
 'Unnamed: 6': True,
 'Unnamed: 7': False,
 'Unnamed: 8': False,
 'Unnamed: 9': False,
 'Unnamed: 10': False,
 'Unnamed: 11': False,
 'Unnamed: 12': False}

### Split Df_summary

I will split df_summary in to new DataFrames. One witch will contain only summaries and one witch will contain BET indices

In [194]:
# split df_summar into two DataFrames
# first DataFrame will contain all rows and first 5 columns and the scond one will contain all rows and the remaining columns begining with the 7th column

df_sumar = df_summar.iloc[:, :6]
df_indices = df_summar.iloc[:, 7:]

In [195]:
# check the shape of df_sumar
df_sumar.shape

(5548, 6)

In [196]:
# view summary info of df_sumar

df_sumar.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5548 entries, 1 to 6715
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  4088 non-null   object
 1   Unnamed: 1  3066 non-null   object
 2   Unnamed: 2  3066 non-null   object
 3   Unnamed: 3  2920 non-null   object
 4   Unnamed: 4  2336 non-null   object
 5   Unnamed: 5  2336 non-null   object
dtypes: object(6)
memory usage: 303.4+ KB

### Df_indices

In [197]:
# check the shape of df_indices

df_indices.shape

(5548, 6)

In [198]:
# view summary info of df_indices

df_indices.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5548 entries, 1 to 6715
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 7   4672 non-null   object
 1   Unnamed: 8   4672 non-null   object
 2   Unnamed: 9   4672 non-null   object
 3   Unnamed: 10  4672 non-null   object
 4   Unnamed: 11  1752 non-null   object
 5   Unnamed: 12  1752 non-null   object
dtypes: object(6)
memory usage: 303.4+ KB

In [199]:
#rename columns of df_indeces

column_name = {'Unnamed: 7': 'indices', 'Unnamed: 8': 'value', 'Unnamed: 9': 'var', 'Unnamed: 10': 'var_percentage', 'Unnamed: 11': 'high', 'Unnamed: 12': 'low'}
df_indices.rename(columns = column_name, inplace = True)

In [200]:
# drop the first three rowas from df_indices

df_indices = df_indices.iloc[3:]

In [201]:
# reset the index on df_indices

df_indices.reset_index(drop = True, inplace = True)

In [202]:
# view summary info on df_indices

df_indices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5545 entries, 0 to 5544
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   indices         4671 non-null   object
 1   value           4671 non-null   object
 2   var             4671 non-null   object
 3   var_percentage  4671 non-null   object
 4   high            1751 non-null   object
 5   low             1751 non-null   object
dtypes: object(6)
memory usage: 260.0+ KB

In [203]:
# drop all rows with null observations on df_indices

df_indices.dropna(how = 'all', inplace = True)

<ipython-input-203-80624be74578>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_indices.dropna(how = 'all', inplace = True)

In [204]:
# fill with zeros null observations on df_indices

df_indices.fillna(0, inplace = True)

<ipython-input-204-f4e6ab2aeb7a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_indices.fillna(0, inplace = True)

In [205]:
# view summary info of df_indices

df_indices.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4816 entries, 0 to 5540
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   indices         4816 non-null   object
 1   value           4816 non-null   object
 2   var             4816 non-null   object
 3   var_percentage  4816 non-null   object
 4   high            4816 non-null   object
 5   low             4816 non-null   object
dtypes: object(6)
memory usage: 263.4+ KB

In [206]:
#df_indices.head(70)

In [207]:
# drop all rows that contain 'Indici / Inidices'

df_indices = df_indices[df_indices['indices'] != 'Indici / Indices']

In [208]:
# drop all rows that contain 'Var.'

df_indices = df_indices[df_indices['var'] != 'Var.']

In [209]:
# view summary info of df_indices

df_indices.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4526 entries, 0 to 5540
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   indices         4526 non-null   object
 1   value           4526 non-null   object
 2   var             4526 non-null   object
 3   var_percentage  4526 non-null   object
 4   high            4526 non-null   object
 5   low             4526 non-null   object
dtypes: object(6)
memory usage: 247.5+ KB

As we can see, all column's data type is object. I will convert numeric columns to float (with two decimals) data type

In [210]:
# convert columns data type to float

col_to_float = ['value', 'var', 'var_percentage', 'high', 'low']

for col in col_to_float:
  df_indices[col] = df_indices[col].astype(float).round(2)

In [211]:
# check info of df_indices again

df_indices.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4526 entries, 0 to 5540
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   indices         4526 non-null   object
 1   value           4526 non-null   float64
 2   var             4526 non-null   float64
 3   var_percentage  4526 non-null   float64
 4   high            4526 non-null   float64
 5   low             4526 non-null   float64
dtypes: float64(5), object(1)
memory usage: 247.5+ KB

In [212]:
# quick view of indices on df

df_indices['indices'].value_counts()

BET LEI           146
BET-XT-TR USD     146
BET-TRN EUR       146
BET-BK EUR        146
BET-NG EUR        146
BET-XT-TR EUR     146
BET-XT EUR        146
BET-FI EUR        146
BETPlus EUR       146
BET-TR EUR        146
BET EUR           146
BET-XT-TRN USD    146
BET-TRN USD       146
BET-BK USD        146
BET-NG USD        146
BET-XT USD        146
BET-TR LEI        146
BET-FI USD        146
BETPlus USD       146
BET-TR USD        146
BET USD           146
BET-XT-TRN LEI    146
BET-TRN LEI       146
BET-BK LEI        146
BET-NG LEI        146
BET-XT-TR LEI     146
BET-XT LEI        146
ROTX LEI          146
BET-FI LEI        146
BETPlus LEI       146
BET-XT-TRN EUR    146
Name: indices, dtype: int64

In [213]:
# check for null observations on df

df_indices.isna().value_counts()

indices  value  var    var_percentage  high   low
False    False  False  False           False  False    4526
dtype: int64

In [214]:
# reset the index on df_indices

df_indices.reset_index(drop = True, inplace = True)

In [215]:
# view summary info of df_indices

df_indices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4526 entries, 0 to 4525
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   indices         4526 non-null   object
 1   value           4526 non-null   float64
 2   var             4526 non-null   float64
 3   var_percentage  4526 non-null   float64
 4   high            4526 non-null   float64
 5   low             4526 non-null   float64
dtypes: float64(5), object(1)
memory usage: 212.3+ KB

In [216]:
# create date column for each file used in dataframe
""" Because data is entered in chronological order on dataframe,
    we will use fictitious calendar dates, only they will be in
    chronological order from the the past until closest to present """

# Specify the start date

start_date = '2023-01-01'

# Calculate the number of records per date (31 records per date)

records_per_date = 31

# Calculate the date range and repeat it to match the DataFrame length

date_range = pd.date_range(start=start_date, periods=len(df_indices) // records_per_date + 1, freq= 'D')
date_column = (date_range.repeat(records_per_date)[:len(df_indices)])

# Assign the date_column to the DataFrame as a new column
df_indices['date'] = date_column[:len(df_indices)]

In [217]:
df_indices

,indices,value,var,var_percentage,high,low,date
0,BET LEI,13396.47,-50.17,-0.37,13570.38,13368.82,2023-01-01
1,BET-TR LEI,23857.69,-88.78,-0.37,24167.27,23809.48,2023-01-01
2,BETPlus LEI,1997.06,-7.17,-0.36,2022.12,1992.99,2023-01-01
3,BET-FI LEI,52206.19,-29.40,-0.06,52492.54,51977.60,2023-01-01
4,ROTX LEI,28804.13,-53.81,-0.19,29165.03,28730.19,2023-01-01
...,...,...,...,...,...,...,...
4521,BET-XT-TR EUR,2149.83,24.46,1.15,0.00,0.00,2023-05-26
4522,BET-NG EUR,719.16,5.68,0.80,0.00,0.00,2023-05-26
4523,BET-BK EUR,2207.82,23.60,1.08,0.00,0.00,2023-05-26
4524,BET-TRN EUR,25542.77,331.74,1.32,0.00,0.00,2023-05-26
4525,BET-XT-TRN EUR,2107.84,23.98,1.15,0.00,0.00,2023-05-26

In [218]:
df_indices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4526 entries, 0 to 4525
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   indices         4526 non-null   object
 1   value           4526 non-null   float64
 2   var             4526 non-null   float64
 3   var_percentage  4526 non-null   float64
 4   high            4526 non-null   float64
 5   low             4526 non-null   float64
 6   date            4526 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 247.6+ KB

In [219]:
# save df to csv file

file_path = 'drive/MyDrive/Colab Notebooks/BVB_project/BVB_indices.csv'

df_indices.to_csv(file_path, index = False)

### Df_sumar

In [220]:
# view summary info on df_sumar

df_sumar.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5548 entries, 1 to 6715
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  4088 non-null   object
 1   Unnamed: 1  3066 non-null   object
 2   Unnamed: 2  3066 non-null   object
 3   Unnamed: 3  2920 non-null   object
 4   Unnamed: 4  2336 non-null   object
 5   Unnamed: 5  2336 non-null   object
dtypes: object(6)
memory usage: 303.4+ KB

In [221]:
# quick view of df_sumar

df_sumar.sample(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
4813,NaN,NaN,NaN,NaN,NaN,NaN
4885,"Exclusiv SIF,FP / Excluding SIF,FP",191417.40411,41857.253091,38603.114611,NaN,NaN
4845,NaN,LEI,USD,EUR,NaN,NaN
2130,NaN,Valoare / Turnover value,NaN,NaN,Volum / Volume,Tranzactii / Trades
5855,Total tranzactionare / Trading totals,NaN,NaN,NaN,NaN,NaN

In [222]:
# rename columns on df_sumar

rename_cols = {'Unnamed: 0': 'info', 'Unnamed: 1': 'value_mil_ron', 'Unnamed: 2': 'value_mil_usd', 'Unnamed: 3': 'value_mil_eur', 'Unnamed: 4': 'volume', 'Unnamed: 5': 'trades'}
df_sumar.rename(columns = rename_cols, inplace = True)

In [223]:
# check if there are any null observations on df

df_sumar.isna().value_counts()

info   value_mil_ron  value_mil_usd  value_mil_eur  volume  trades
False  False          False          False          False   False     2190
       True           True           True           True    True      1460
True   True           True           True           True    True       876
False  False          False          False          True    True       438
True   False          False          False          True    True       292
                      True           True           False   False      146
       True           False          True           True    True       146
dtype: int64

In [224]:
# drop rows that are only with null obs

df_sumar.dropna(how = 'all', inplace = True)

In [225]:
# quick view of df

df_sumar

,info,value_mil_ron,value_mil_usd,value_mil_eur,volume,trades
1,NaN,NaN,SUMARUL TRANZACTIILOR din 03.02.2022 / TRADING...,NaN,NaN,NaN
6,Capitalizare Bursiera / Market Capitalization,NaN,NaN,NaN,NaN,NaN
7,NaN,mil. LEI,mil. USD,mil. EUR,NaN,NaN
8,Total,242823.14536,55382.174788,49097.831522,NaN,NaN
9,"Exclusiv SIF,FP / Excluding SIF,FP",224340.048269,51166.620657,45360.626053,NaN,NaN
...,...,...,...,...,...,...
6708,TOTAL,0,0,0,0,0
6710,PIATA LA TERMEN / DERIVATIVES MARKET,NaN,NaN,NaN,NaN,NaN
6711,Futures,0,0,0,0,0
6712,TOTAL,0,0,0,0,0
6715,TOTAL GENERAL / GENERAL TOTAL,78111679.203,16874417.6192,15729295.0369,41379484,9576

In [226]:
# reset the index on df_indices

df_sumar.reset_index(drop = True, inplace = True)

In [227]:
# create date column for each file used in dataframe
""" Because data is entered in chronological order on dataframe,
    we will use fictitious calendar dates, only they will be in
    chronological order from the the past until closest to present """

# Specify the start date

start_date = '2023-01-01'

# Calculate the number of records per date (31 records per date)

records_per_date = 32

# Calculate the date range and repeat it to match the DataFrame length

date_range = pd.date_range(start = start_date, periods = len(df_sumar) // records_per_date + 1, freq= 'D')
date_column = (date_range.repeat(records_per_date)[:len(df_sumar)])

# Assign the date_column to the DataFrame as a new column
df_sumar['date'] = date_column[:len(df_sumar)]

In [228]:
# replace strings in df_sumar['info']

replace_strings = {'Total ': 'Market Cap', 'Exclusiv SIF,FP / Excluding SIF,FP': 'Cap Excluding SIF and FP', 'Capitalizare SIF,FP / Capitalization SIF,FP': 'Cap SIF and FP',
                   'Actiuni / Shares': 'Total trading equites Shares', 'Drepturi/Rights': 'Total trading equites Rights', 'Obligatiuni / Bonds': 'Total trading Bonds',
                   'Unitati de fond / Units': 'Total trading Units', 'Structurate / Structured': 'Total trading Structured', 'Futures': 'Total trading Futures',
                   'TOTAL GENERAL / GENERAL TOTAL': 'Total trading'}
df_sumar['info'] = df_sumar['info'].replace(replace_strings)

In [229]:
# view summary info of df

df_sumar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4672 entries, 0 to 4671
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   info           4088 non-null   object
 1   value_mil_ron  3066 non-null   object
 2   value_mil_usd  3066 non-null   object
 3   value_mil_eur  2920 non-null   object
 4   volume         2336 non-null   object
 5   trades         2336 non-null   object
 6   date           4672 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(6)
memory usage: 255.6+ KB

In [230]:
# drop rows from df we don't need and with no data

rows_to_drop = ['Capitalizare Bursiera / Market Capitalization', 'Total tranzactionare / Trading totals', 'TITLURI DE CAPITAL / EQUITIES', 'TITLURI DE CREDIT / DEBT SECURITIES',
                'OPC / Collective Investment Undertakings (Funds)', 'PRODUSE STRUCTURATE / STRUCTURED', 'TOTAL', 'ALTE INSTRUMENTE FINANCIARE INTERNATIONALE / OTHER INTERNATIONAL FINANCIAL INSTRUMENTS',
                'Categoria A / A Category', 'Categoria B / B Category', 'PIATA LA TERMEN / DERIVATIVES MARKET', 'mil. USD', 'Valoare / Turnover value', 'USD']

df_sumar = df_sumar[~df_sumar['info'].isin(rows_to_drop)]
df_sumar = df_sumar[~df_sumar['value_mil_usd'].isin(rows_to_drop)]
df_sumar = df_sumar[~df_sumar['value_mil_ron'].isin(rows_to_drop)]

In [231]:
# drop rows on column 'value_mil_usd' witch contain a string

common_str = 'SUMARUL TRANZACTIILOR'
df_sumar = df_sumar[~df_sumar['value_mil_usd'].str.contains(common_str, na=False)]

In [232]:
# reset the index on df_indices

df_sumar.reset_index(drop = True, inplace = True)

In [233]:
# replace null obs with zeros on volume and trades columns of df

df_sumar['volume'] = df_sumar['volume'].fillna(0)
df_sumar['trades'] = df_sumar['trades'].fillna(0)

In [234]:
# convert value columns data type into float

col_to_floats = ['value_mil_usd', 'value_mil_ron', 'value_mil_eur']

for col in col_to_floats:
  df_sumar[col] = df_sumar[col].astype(float).round(2)

# convert volume and trades columns data type into integers

col_to_int = ['volume', 'trades']

for col in col_to_int:
  df_sumar[col] = df_sumar[col].astype(int)

In [235]:
# view summary info of df

df_sumar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1606 entries, 0 to 1605
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   info           1606 non-null   object
 1   value_mil_ron  1606 non-null   float64
 2   value_mil_usd  1606 non-null   float64
 3   value_mil_eur  1606 non-null   float64
 4   volume         1606 non-null   int64
 5   trades         1606 non-null   int64
 6   date           1606 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(2), object(1)
memory usage: 88.0+ KB

In [236]:
df_sumar

,info,value_mil_ron,value_mil_usd,value_mil_eur,volume,trades,date
0,Market Cap,242823.15,55382.17,49097.83,0,0,2023-01-01
1,Cap Excluding SIF and FP,224340.05,51166.62,45360.63,0,0,2023-01-01
2,Cap SIF and FP,18483.10,4215.55,3737.21,0,0,2023-01-01
3,Total trading equites Shares,45335453.23,10339936.87,9166640.36,45482075,4848,2023-01-01
4,Total trading equites Rights,0.00,0.00,0.00,0,0,2023-01-01
...,...,...,...,...,...,...,...
1601,Total trading equites Shares,0.00,0.00,0.00,0,0,2023-05-26
1602,Total trading Units,596562.47,128875.02,120129.37,31940,497,2023-05-26
1603,Total trading Structured,1655922.00,357727.80,333451.87,707160,505,2023-05-26
1604,Total trading Futures,0.00,0.00,0.00,0,0,2023-05-26
1605,Total trading,78111679.20,16874417.62,15729295.04,41379484,9576,2023-05-26

In [237]:
# save df to csv file

file_path = 'drive/MyDrive/Colab Notebooks/BVB_project/BVB_summary.csv'

df_sumar.to_csv(file_path, index = False)

## Df_equities

In [238]:
# view summary info on df

df_equities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27522 entries, 0 to 27521
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   0 non-null      float64
 1   Unnamed: 1   13836 non-null  object
 2   Unnamed: 2   13122 non-null  object
 3   Unnamed: 3   19828 non-null  object
 4   Unnamed: 4   9755 non-null   object
 5   Unnamed: 5   19828 non-null  object
 6   Unnamed: 6   19828 non-null  object
 7   Unnamed: 7   19828 non-null  object
 8   Unnamed: 8   19828 non-null  object
 9   Unnamed: 9   19828 non-null  object
 10  Unnamed: 10  19828 non-null  object
 11  Unnamed: 11  20412 non-null  object
 12  Unnamed: 12  20412 non-null  object
 13  Unnamed: 13  20379 non-null  object
 14  Unnamed: 14  10160 non-null  object
 15  Unnamed: 15  10160 non-null  object
dtypes: float64(1), object(15)
memory usage: 3.4+ MB

In [239]:
# drop columns only with null obs

df_equities.dropna(axis = 1, how = 'all', inplace = True)

In [240]:
# drop rows only with null obs

df_equities.dropna(how = 'all', inplace = True)

In [241]:
# preview of df

df_equities.sample(10)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
19187,NaN,NaN,Regular,NaN,8.32,0.97,8.3,8.32,8.24,8.31,13999,116279.11,89,NaN,NaN
3326,NaN,NaN,Regular,NaN,0.1152,-4,0.1198,0.1212,0.113,0.1158,2533287,293310.239,219,NaN,NaN
6887,NaN,NaN,Regular,NaN,0.268,6.77,0.257,0.269,0.257,0.261,46875,12217.107,11,NaN,NaN
5415,IARV,IAR SA Brasov,TOTAL,2.5,10.95,0.92,10.9,10.95,10.9,10.9484,159,1740.8,7,12.15,8.86
25945,STZ,SINTEZA S.A.,TOTAL,0.15,0.304,-11.11,0.304,0.304,0.304,0.304,1676,509.504,2,0.4,0.3
26801,NaN,NaN,Regular,NaN,2.42,1.26,2.38,2.42,2.38,2.4,54380,130652.29,30,NaN,NaN
9256,IARV,IAR SA Brasov,TOTAL,2.5,10.6,-5.78,10.95,10.95,10.6,10.6879,4510,48202.85,49,12.15,8.86
9081,RRC,ROMPETROL RAFINARE S.A.,TOTAL,0.1,0.084,0.6,0.082,0.084,0.082,0.0834,47972,4003.242,10,0.0915,0.065
14611,NaN,NaN,Regular,NaN,0.131,-0.76,0.132,0.132,0.131,0.131,4900,644.1,2,NaN,NaN
4120,NaN,NaN,Regular,NaN,23.2,0,23.1,23.2,22.8,23.2,1121,25957.6,13,NaN,NaN

In [242]:
# drop rows from df we don't need and with no data

rows_to_drop_df_eq = ['TITLURI DE CAPITAL / EQUITIES', 'EMISE DE ENTITATI DIN ROMANIA / DOMESTIC', 'ACTIUNI / SHARES', 'Premium',
                      'Regular', 'Societati de Investitii Financiare / Financial Investments Funds (SIF)', 'Standard', 'Oferta Publica de Cumparare / Tender Offer',
                      'INTERNATIONALE / FOREIGN',
                      'Pretul de inchidere din piata principala a rezultat dintr-o tranzactie cross pentru urmatoarele simboluri / The closing price in the main market was given by a cross trade for the following symbols:']

df_equities = df_equities[~df_equities['Unnamed: 1'].isin(rows_to_drop_df_eq)]
df_equities = df_equities[~df_equities['Unnamed: 3'].isin(rows_to_drop_df_eq)]
#df_sumar = df_sumar[~df_sumar['value_mil_ron'].isin(rows_to_drop)]

In [243]:
# rename the columns in df

rename_col = df_equities.iloc[0]

df_equities.columns = rename_col

In [244]:
# rename the columns in df

columns_renamed = ['Symbol', 'Company_name',
       'Market', 'Face_value', 'Close ',
       'Change_%', 'Open', 'High', 'Low',
       'Avg_price', 'Volume', 'Turnover',
       'No_of_trades', '52_High', '52_Min']
df_equities.columns = columns_renamed
df_equities.rename_axis('Index')

,Symbol,Company_name,Market,Face_value,Close,Change_%,Open,High,Low,Avg_price,Volume,Turnover,No_of_trades,52_High,52_Min
Index,,,,,,,,,,,,,,,
9,Simbol / Symbol,Denumire societate / Company name,Sectiune piata / Market,VN / Face value,Inch./ Close,Var / Change (%),Desc. / Open,Max. / High,Min. / Low,Pr.med. / Avg.,Nr.actiuni / Volume,Val. totala / Turnover,Nr.trz. / No. of trades,52 Max / 52 High,52 Min / 52 Min
10,ALR,ALRO S.A.,TOTAL,0.5,2,-0.99,2.03,2.03,2,2.0062,39029,78303.02,35,3.28,1.8
12,ATB,ANTIBIOTICE S.A.,TOTAL,0.1,0.588,-0.68,0.592,0.592,0.584,0.5861,6315,3701.652,11,0.61,0.496
14,AQ,AQUILA PART PROD COM,TOTAL,0.15,5.38,0,5.38,5.4,5.34,5.3571,12244,65592.76,31,5.6,5.2
16,TLV,BANCA TRANSILVANIA S.A.,TOTAL,1,2.69,0,2.695,2.705,2.665,2.6942,1444366,3891507.03,405,3.055,2.145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27517,SAFE,SAFETECH INNOVATIONS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27518,SCD,ZENTIVA S.A.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27519,SFG,Sphera Franchise Group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27520,STZ,SINTEZA S.A.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27521,TUFE,TURISM FELIX S.A.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [245]:
# drop rows in df by a specific strig

rows_to_drop_df = ['Simbol / Symbol',
                      'Pretul de inchidere din piata principala a rezultat dintr-o tranzactie cross pentru urmatoarele simboluri / The closing price in the main market was given by a cross trade for the following symbols:']

df_equities = df_equities[~df_equities['Symbol'].isin(rows_to_drop_df)]
#df_equities = df_equities[~df_equities['Unnamed: 3'].isin(rows_to_drop_df_eq)]

In [246]:
# preview of df

df_equities

,Symbol,Company_name,Market,Face_value,Close,Change_%,Open,High,Low,Avg_price,Volume,Turnover,No_of_trades,52_High,52_Min
10,ALR,ALRO S.A.,TOTAL,0.5,2,-0.99,2.03,2.03,2,2.0062,39029,78303.02,35,3.28,1.8
12,ATB,ANTIBIOTICE S.A.,TOTAL,0.1,0.588,-0.68,0.592,0.592,0.584,0.5861,6315,3701.652,11,0.61,0.496
14,AQ,AQUILA PART PROD COM,TOTAL,0.15,5.38,0,5.38,5.4,5.34,5.3571,12244,65592.76,31,5.6,5.2
16,TLV,BANCA TRANSILVANIA S.A.,TOTAL,1,2.69,0,2.695,2.705,2.665,2.6942,1444366,3891507.03,405,3.055,2.145
18,BIO,BIOFARM S.A.,TOTAL,0.1,0.812,-0.25,0.814,0.814,0.8,0.808,24565,19850.25,24,0.842,0.468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27517,SAFE,SAFETECH INNOVATIONS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27518,SCD,ZENTIVA S.A.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27519,SFG,Sphera Franchise Group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27520,STZ,SINTEZA S.A.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27521,TUFE,TURISM FELIX S.A.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [247]:
# drop rows with null values on specific columns

column_name = 'Market'

df_equities = df_equities.dropna(subset=[column_name])
df_equities

,Symbol,Company_name,Market,Face_value,Close,Change_%,Open,High,Low,Avg_price,Volume,Turnover,No_of_trades,52_High,52_Min
10,ALR,ALRO S.A.,TOTAL,0.5,2,-0.99,2.03,2.03,2,2.0062,39029,78303.02,35,3.28,1.8
12,ATB,ANTIBIOTICE S.A.,TOTAL,0.1,0.588,-0.68,0.592,0.592,0.584,0.5861,6315,3701.652,11,0.61,0.496
14,AQ,AQUILA PART PROD COM,TOTAL,0.15,5.38,0,5.38,5.4,5.34,5.3571,12244,65592.76,31,5.6,5.2
16,TLV,BANCA TRANSILVANIA S.A.,TOTAL,1,2.69,0,2.695,2.705,2.665,2.6942,1444366,3891507.03,405,3.055,2.145
18,BIO,BIOFARM S.A.,TOTAL,0.1,0.812,-0.25,0.814,0.814,0.8,0.808,24565,19850.25,24,0.842,0.468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27481,VNC,VRANCART SA,TOTAL,0.1,0.168,-2.33,0.172,0.172,0.168,0.1703,160193,27282.251,36,0.177,0.148
27483,SCD,ZENTIVA S.A.,TOTAL,0.1,2.3,4.55,2.22,2.3,2.2,2.2617,7331,16581.1,16,2.32,1.8
27496,DIGI,Digi Communications N.V.,TOTAL,NaN,35.8,-0.28,35.8,35.9,35.6,35.8218,3799,136087.1,80,36.9,29.2
27498,EBS,Erste Group Bank AG,TOTAL,NaN,160.9,1.13,159.6,161.4,159.15,160.4068,2762,443043.75,49,182,109
27500,WINE,PURCARI WINERIES PUBLIC COMPANY LIMITED,TOTAL,NaN,12.54,2.79,12.12,12.72,12.12,12.5315,73692,923475.7,259,12.54,8.39

In [248]:
# drop rows with null values on specific columns

column_name_n = 'Company_name'

df_equities = df_equities.dropna(subset=[column_name_n])
df_equities

,Symbol,Company_name,Market,Face_value,Close,Change_%,Open,High,Low,Avg_price,Volume,Turnover,No_of_trades,52_High,52_Min
10,ALR,ALRO S.A.,TOTAL,0.5,2,-0.99,2.03,2.03,2,2.0062,39029,78303.02,35,3.28,1.8
12,ATB,ANTIBIOTICE S.A.,TOTAL,0.1,0.588,-0.68,0.592,0.592,0.584,0.5861,6315,3701.652,11,0.61,0.496
14,AQ,AQUILA PART PROD COM,TOTAL,0.15,5.38,0,5.38,5.4,5.34,5.3571,12244,65592.76,31,5.6,5.2
16,TLV,BANCA TRANSILVANIA S.A.,TOTAL,1,2.69,0,2.695,2.705,2.665,2.6942,1444366,3891507.03,405,3.055,2.145
18,BIO,BIOFARM S.A.,TOTAL,0.1,0.812,-0.25,0.814,0.814,0.8,0.808,24565,19850.25,24,0.842,0.468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27481,VNC,VRANCART SA,TOTAL,0.1,0.168,-2.33,0.172,0.172,0.168,0.1703,160193,27282.251,36,0.177,0.148
27483,SCD,ZENTIVA S.A.,TOTAL,0.1,2.3,4.55,2.22,2.3,2.2,2.2617,7331,16581.1,16,2.32,1.8
27496,DIGI,Digi Communications N.V.,TOTAL,NaN,35.8,-0.28,35.8,35.9,35.6,35.8218,3799,136087.1,80,36.9,29.2
27498,EBS,Erste Group Bank AG,TOTAL,NaN,160.9,1.13,159.6,161.4,159.15,160.4068,2762,443043.75,49,182,109
27500,WINE,PURCARI WINERIES PUBLIC COMPANY LIMITED,TOTAL,NaN,12.54,2.79,12.12,12.72,12.12,12.5315,73692,923475.7,259,12.54,8.39

In [249]:
# reset the index on df

df_equities.reset_index(drop = True, inplace = True)

In [250]:
# drop "Market" column on df, because we do not need it any more

df_equities = df_equities.drop('Market', axis = 1)

df_equities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9593 entries, 0 to 9592
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Symbol        9593 non-null   object
 1   Company_name  9593 non-null   object
 2   Face_value    9155 non-null   object
 3   Close         9593 non-null   object
 4   Change_%      9593 non-null   object
 5   Open          9593 non-null   object
 6   High          9593 non-null   object
 7   Low           9593 non-null   object
 8   Avg_price     9593 non-null   object
 9   Volume        9593 non-null   object
 10  Turnover      9593 non-null   object
 11  No_of_trades  9576 non-null   object
 12  52_High       9576 non-null   object
 13  52_Min        9576 non-null   object
dtypes: object(14)
memory usage: 1.0+ MB

In [251]:
# fill null values with 0 on face_value column

df_equities['Face_value'].fillna(0, inplace = True)

In [252]:
# check for null ob in df

df_equities.isna().value_counts()

Symbol  Company_name  Face_value  Close   Change_%  Open   High   Low    Avg_price  Volume  Turnover  No_of_trades  52_High  52_Min
False   False         False       False   False     False  False  False  False      False   False     False         False    False     9576
                                                                                                      True          True     True        17
dtype: int64

In [253]:
# check the null obs on df

null_rows = df_equities[df_equities.isnull().any(axis=1)]
null_rows

,Symbol,Company_name,Face_value,Close,Change_%,Open,High,Low,Avg_price,Volume,Turnover,No_of_trades,52_High,52_Min
304,MCABR01,Drepturi preferinta ROMCAB,0.0010,-50,0.002,0.002,0.0005,0.001,2342637,2712.289,45,NaN,NaN,NaN
684,SNP,OMV PETROM S.A.,0.4300,-7.43,0.43,0.43,0.43,0.43,1777067726,764139122.18,153,NaN,NaN,NaN
1526,EVER,EVERGENT INVESTMENTS S.A.,1.4100,3.3,1.41,1.41,1.41,1.41,19625000,27671250,162,NaN,NaN,NaN
1772,BNETR16,Drepturi preferinta 01.2023,0.0010,0,0.003,0.003,0.0005,0.001,22752826,23531.952,215,NaN,NaN,NaN
1833,BNETR16,Drepturi preferinta 01.2023,0.0010,100,0.001,0.0015,0.0005,0.001,24208404,21884.4905,182,NaN,NaN,NaN
1898,BNETR16,Drepturi preferinta 01.2023,0.0005,-50,0.001,0.001,0.0005,0.0005,24270213,14486.3615,107,NaN,NaN,NaN
1961,BNETR16,Drepturi preferinta 01.2023,0.0005,0,0.0005,0.0015,0.0005,0.0005,212406804,143119.5145,245,NaN,NaN,NaN
3581,FP,FONDUL PROPRIETATEA,2.1900,1.86,2.19,2.19,2.19,2.19,132875150,290996578.5,1218,NaN,NaN,NaN
3842,CEON,CEMACON SA,0.4800,1.48,0.48,0.48,0.48,0.48,22111193,10613372.64,199,NaN,NaN,NaN
3843,ONE,ONE UNITED PROPERTIES,0.7900,-7.82,0.79,0.79,0.79,0.79,31000000,24490000,39,NaN,NaN,NaN
4106,TUFE,TURISM FELIX S.A.,0.3100,4.03,0.31,0.31,0.31,0.31,143752429,44563252.99,1,NaN,NaN,NaN
4477,NAPO,SOCIETATEA DE CONSTRUCTII NAPOCA SA,4.3433,3.41,4.3433,4.3433,4.3433,4.3433,59566,258713.0078,14,NaN,NaN,NaN
7213,BRD,BRD - GROUPE SOCIETE GENERALE S.A.,12.4200,-1.11,12.42,12.42,12.42,12.42,3000,37260,1,NaN,NaN,NaN
7560,H2O,S.P.E.E.H. HIDROELECTRICA S.A.,104.0000,0,104,104,104,104,71766542,7463720368,109,NaN,NaN,NaN
7561,H2O,S.P.E.E.H. HIDROELECTRICA S.A.,100.8800,0,104,104,100.88,101.3002,17941635,1817491671.84,51865,NaN,NaN,NaN
8486,TTS,TTS (TRANSPORT TRADE SERVICES),17.2500,-13.1,17.25,17.25,17.25,17.25,2757300,47563425,44,NaN,NaN,NaN
9378,SAFE,SAFETECH INNOVATIONS,2.5000,-13.79,2.5,2.5,2.5,2.5,6864400,17161000,67,NaN,NaN,NaN

In [254]:
# fill null obs with zeros on df

df_equities.fillna(0, inplace = True)

df_equities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9593 entries, 0 to 9592
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Symbol        9593 non-null   object
 1   Company_name  9593 non-null   object
 2   Face_value    9593 non-null   float64
 3   Close         9593 non-null   float64
 4   Change_%      9593 non-null   float64
 5   Open          9593 non-null   float64
 6   High          9593 non-null   float64
 7   Low           9593 non-null   float64
 8   Avg_price     9593 non-null   float64
 9   Volume        9593 non-null   float64
 10  Turnover      9593 non-null   float64
 11  No_of_trades  9593 non-null   int64
 12  52_High       9593 non-null   float64
 13  52_Min        9593 non-null   float64
dtypes: float64(11), int64(1), object(2)
memory usage: 1.0+ MB

In [255]:
# preview of df

df_equities

,Symbol,Company_name,Face_value,Close,Change_%,Open,High,Low,Avg_price,Volume,Turnover,No_of_trades,52_High,52_Min
0,ALR,ALRO S.A.,0.50,2.000,-0.99,2.030,2.030,2.000,2.0062,39029.0,78303.020,35,3.280,1.800
1,ATB,ANTIBIOTICE S.A.,0.10,0.588,-0.68,0.592,0.592,0.584,0.5861,6315.0,3701.652,11,0.610,0.496
2,AQ,AQUILA PART PROD COM,0.15,5.380,0.00,5.380,5.400,5.340,5.3571,12244.0,65592.760,31,5.600,5.200
3,TLV,BANCA TRANSILVANIA S.A.,1.00,2.690,0.00,2.695,2.705,2.665,2.6942,1444366.0,3891507.030,405,3.055,2.145
4,BIO,BIOFARM S.A.,0.10,0.812,-0.25,0.814,0.814,0.800,0.8080,24565.0,19850.250,24,0.842,0.468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9588,VNC,VRANCART SA,0.10,0.168,-2.33,0.172,0.172,0.168,0.1703,160193.0,27282.251,36,0.177,0.148
9589,SCD,ZENTIVA S.A.,0.10,2.300,4.55,2.220,2.300,2.200,2.2617,7331.0,16581.100,16,2.320,1.800
9590,DIGI,Digi Communications N.V.,0.00,35.800,-0.28,35.800,35.900,35.600,35.8218,3799.0,136087.100,80,36.900,29.200
9591,EBS,Erste Group Bank AG,0.00,160.900,1.13,159.600,161.400,159.150,160.4068,2762.0,443043.750,49,182.000,109.000
9592,WINE,PURCARI WINERIES PUBLIC COMPANY LIMITED,0.00,12.540,2.79,12.120,12.720,12.120,12.5315,73692.0,923475.700,259,12.540,8.390

In [256]:
# create a date column and assign the same date to all observations in a range from the first observation to the moment when the observation is repeated in the dataframe.

current_date = None
date_counter = 0

# Initialize a list to store the new dates
new_dates = []

# Iterate through the DataFrame
for index, row in df_equities.iterrows():
    name = row['Symbol']

    if name == 'ALR' or current_date is None:
        # If the name is 'Alice' or current_date is None, assign the current date
        if current_date is None:
            current_date = pd.Timestamp('2023-01-01')
        else:
            current_date += pd.DateOffset(days=1)


    new_dates.append(current_date)

# Create a new column with the calculated dates
df_equities['Date'] = new_dates

# Display the DataFrame with the new column
df_equities

,Symbol,Company_name,Face_value,Close,Change_%,Open,High,Low,Avg_price,Volume,Turnover,No_of_trades,52_High,52_Min,Date
0,ALR,ALRO S.A.,0.50,2.000,-0.99,2.030,2.030,2.000,2.0062,39029.0,78303.020,35,3.280,1.800,2023-01-01
1,ATB,ANTIBIOTICE S.A.,0.10,0.588,-0.68,0.592,0.592,0.584,0.5861,6315.0,3701.652,11,0.610,0.496,2023-01-01
2,AQ,AQUILA PART PROD COM,0.15,5.380,0.00,5.380,5.400,5.340,5.3571,12244.0,65592.760,31,5.600,5.200,2023-01-01
3,TLV,BANCA TRANSILVANIA S.A.,1.00,2.690,0.00,2.695,2.705,2.665,2.6942,1444366.0,3891507.030,405,3.055,2.145,2023-01-01
4,BIO,BIOFARM S.A.,0.10,0.812,-0.25,0.814,0.814,0.800,0.8080,24565.0,19850.250,24,0.842,0.468,2023-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9588,VNC,VRANCART SA,0.10,0.168,-2.33,0.172,0.172,0.168,0.1703,160193.0,27282.251,36,0.177,0.148,2023-05-26
9589,SCD,ZENTIVA S.A.,0.10,2.300,4.55,2.220,2.300,2.200,2.2617,7331.0,16581.100,16,2.320,1.800,2023-05-26
9590,DIGI,Digi Communications N.V.,0.00,35.800,-0.28,35.800,35.900,35.600,35.8218,3799.0,136087.100,80,36.900,29.200,2023-05-26
9591,EBS,Erste Group Bank AG,0.00,160.900,1.13,159.600,161.400,159.150,160.4068,2762.0,443043.750,49,182.000,109.000,2023-05-26
9592,WINE,PURCARI WINERIES PUBLIC COMPANY LIMITED,0.00,12.540,2.79,12.120,12.720,12.120,12.5315,73692.0,923475.700,259,12.540,8.390,2023-05-26

In [257]:
# reset the index on df

df_equities.reset_index(drop = True, inplace = True)

In [258]:
# view summary info on df

df_equities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9593 entries, 0 to 9592
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Symbol        9593 non-null   object
 1   Company_name  9593 non-null   object
 2   Face_value    9593 non-null   float64
 3   Close         9593 non-null   float64
 4   Change_%      9593 non-null   float64
 5   Open          9593 non-null   float64
 6   High          9593 non-null   float64
 7   Low           9593 non-null   float64
 8   Avg_price     9593 non-null   float64
 9   Volume        9593 non-null   float64
 10  Turnover      9593 non-null   float64
 11  No_of_trades  9593 non-null   int64
 12  52_High       9593 non-null   float64
 13  52_Min        9593 non-null   float64
 14  Date          9593 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(11), int64(1), object(2)
memory usage: 1.1+ MB

In [259]:
# save df to csv file

file_path = 'drive/MyDrive/Colab Notebooks/BVB_project/BVB_equities.csv'

df_equities.to_csv(file_path, index = False)

## Df_bonds

In [260]:
# view summary info on df

df_bonds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29054 entries, 0 to 29053
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   7062 non-null   object
 1   Unnamed: 1   3821 non-null   object
 2   Unnamed: 2   8225 non-null   object
 3   Unnamed: 3   8003 non-null   object
 4   Unnamed: 4   8003 non-null   object
 5   Unnamed: 5   8003 non-null   object
 6   Unnamed: 6   7565 non-null   object
 7   Unnamed: 7   7419 non-null   object
 8   Unnamed: 8   7419 non-null   object
 9   Unnamed: 9   7419 non-null   object
 10  Unnamed: 10  7419 non-null   object
 11  Unnamed: 11  7419 non-null   object
dtypes: object(12)
memory usage: 2.7+ MB

In [261]:
# prewview of df

df_bonds

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,TITLURI DE CREDIT / DEBT SECURITIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,EMISE DE ENTITATI DIN ROMANIA / DOMESTIC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
29049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29053,Simb\nSymbol,Denumire societate\nCompany name,Sectiune piata\nMarket,Inch.\nClose (RON),Var\nChange\n%,Desc.\nOpen,Max.\nHigh,Min.\nLow,Pr.med.\nAverage \nprice,Nr. actiuni\nVolume,Val. totala\nTurnover (RON),Nr.trz\nNo. of trades

In [262]:
# drop null obs

df_bonds.dropna(how = 'all', inplace = True)

In [263]:
# drop rows on df

rows_to_drop_df_bonds = ['TITLURI DE CREDIT / DEBT SECURITIES', 'EMISE DE ENTITATI DIN ROMANIA / DOMESTIC','OBLIGATIUNI / BONDS', 'OBLIGATIUNI MUNICIPALE (MUNICIPAL BONDS)',
                         'OBLIGATIUNI CORPORATIVE (CORPORATE BONDS)', 'TITLURI DE STAT (GOVERNMENT BONDS)', 'INTERNATIONALE / FOREIGN', 'OBLIGATIUNI INTERNATIONALE (INTERNATIONAL BONDS)',
                         'TOTAL', 'Denumire emitent', 'Company name', 'Denumire societate / Company name', ' Simbol / Symbol ', 'Denumire societate Company name',
                         'Pretul de inchidere din piata principala a rezultat dintr-o tranzactie cross pentru urmatoarele simboluri / The closing price in the main market was given by a cross trade for the following symbols: ']

df_bonds = df_bonds[~df_bonds['Unnamed: 0'].isin(rows_to_drop_df_bonds)]
df_bonds = df_bonds[~df_bonds['Unnamed: 1'].isin(rows_to_drop_df_bonds)]

In [264]:
# rename columns on df

rename_columns = ['Symbol', 'Company_name', 'Market', 'Volumne', 'Turnover_value', 'Trades', 'Clean_price_avg_%', 'Clean_price_open_%', 'Clean_price_high_%',
                  'Clean_price_low_%', 'Clean_price_close_%', 'Change_%']
df_bonds.columns = rename_columns

In [265]:
# check for null obs on df

nulls = df_bonds[df_bonds.isnull().any(axis = 1)]
nulls

,Symbol,Company_name,Market,Volumne,Turnover_value,Trades,Clean_price_avg_%,Clean_price_open_%,Clean_price_high_%,Clean_price_low_%,Clean_price_close_%,Change_%
16,NaN,NaN,EORDB,48,122967.62,8,102.8,102,103.14,102,103.14,1.02
18,NaN,NaN,EORDB,5,13147.74,1,104.1,104.1,104.1,104.1,104.1,0.34
20,NaN,NaN,ORDB,95,9552.4,6,98.9,99.28,99.28,98.81,98.81,-0.47
27,R2212A,NaN,TOTAL,103,10298.97,2,99.4,99.4,99.4,99.4,99.4,0
28,R2403A,NaN,TOTAL,100,9784.6,2,95.126,95.15,95.15,95.11,95.11,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...
28976,NaN,ORV27,PRIMARIA ORASULUI ORAVITA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28977,NaN,R2403A,MINISTERUL FINANTELOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28978,NaN,R2408C,MINISTERUL FINANTELOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28979,NaN,R2608A,MINISTERUL FINANTELOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28980,NaN,SRE28,PRIMARIA ORASULUI SIRET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [266]:
# Identify duplicated rows (on any axis) and keep the first occurrence
df_bonds = df_bonds[~df_bonds.duplicated(subset = ['Volumne', 'Turnover_value', 'Trades'])]

# Display the updated DataFrame
df_bonds

,Symbol,Company_name,Market,Volumne,Turnover_value,Trades,Clean_price_avg_%,Clean_price_open_%,Clean_price_high_%,Clean_price_low_%,Clean_price_close_%,Change_%
15,IMP26E,IMPACT DEVELOPER & CONTRACTOR 2026 EUR,TOTAL,48,122967.62,8,102.8,102,103.14,102,103.14,1.02
17,PBK28E,Patria Bank Obligatiuni 2028 EUR,TOTAL,5,13147.74,1,104.1,104.1,104.1,104.1,104.1,0.34
19,BRK26,SSIF BRK FINANCIAL GROUP - Ob. 2026,TOTAL,95,9552.4,6,98.9,99.28,99.28,98.81,98.81,-0.47
26,R2210A,MINISTERUL FINANTELOR,TOTAL,12,1206.24,3,99.42,99.4399,99.4399,99.4,99.4,0.71
27,R2212A,NaN,TOTAL,103,10298.97,2,99.4,99.4,99.4,99.4,99.4,0
...,...,...,...,...,...,...,...,...,...,...,...,...
28945,R2406AE,MINISTERUL FINANTELOR - EURO,TOTAL,14,6881.28,2,98.5011,98.5011,98.5011,98.5011,98.5011,-0.74
28947,R2312A,MINISTERUL FINANTELOR PUBLICE,TOTAL,920,94299.58,14,99.3995,99.4,99.4699,99.38,99.4699,0
28948,R2408A,NaN,TOTAL,369,36333.82,10,98.0755,98,98.3788,98,98.3788,0.39
28949,R2508AE,NaN,TOTAL,61,28865.64,3,95.1518,95,95.2988,95,95.2987,0.74
28950,R2512AE,NaN,TOTAL,16806,7882040.1,23,93.0444,93,93.25,93,93,0.08

In [267]:
# drop rows with null obs in specific columns on df

cols_to_check = ['Volumne', 'Turnover_value']

df_bonds = df_bonds[~df_bonds[cols_to_check].isnull().any(axis = 1)]
df_bonds

,Symbol,Company_name,Market,Volumne,Turnover_value,Trades,Clean_price_avg_%,Clean_price_open_%,Clean_price_high_%,Clean_price_low_%,Clean_price_close_%,Change_%
15,IMP26E,IMPACT DEVELOPER & CONTRACTOR 2026 EUR,TOTAL,48,122967.62,8,102.8,102,103.14,102,103.14,1.02
17,PBK28E,Patria Bank Obligatiuni 2028 EUR,TOTAL,5,13147.74,1,104.1,104.1,104.1,104.1,104.1,0.34
19,BRK26,SSIF BRK FINANCIAL GROUP - Ob. 2026,TOTAL,95,9552.4,6,98.9,99.28,99.28,98.81,98.81,-0.47
26,R2210A,MINISTERUL FINANTELOR,TOTAL,12,1206.24,3,99.42,99.4399,99.4399,99.4,99.4,0.71
27,R2212A,NaN,TOTAL,103,10298.97,2,99.4,99.4,99.4,99.4,99.4,0
...,...,...,...,...,...,...,...,...,...,...,...,...
28945,R2406AE,MINISTERUL FINANTELOR - EURO,TOTAL,14,6881.28,2,98.5011,98.5011,98.5011,98.5011,98.5011,-0.74
28947,R2312A,MINISTERUL FINANTELOR PUBLICE,TOTAL,920,94299.58,14,99.3995,99.4,99.4699,99.38,99.4699,0
28948,R2408A,NaN,TOTAL,369,36333.82,10,98.0755,98,98.3788,98,98.3788,0.39
28949,R2508AE,NaN,TOTAL,61,28865.64,3,95.1518,95,95.2988,95,95.2987,0.74
28950,R2512AE,NaN,TOTAL,16806,7882040.1,23,93.0444,93,93.25,93,93,0.08

In [268]:
df_bonds.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3555 entries, 15 to 28950
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Symbol               3552 non-null   object
 1   Company_name         1239 non-null   object
 2   Market               3555 non-null   object
 3   Volumne              3555 non-null   object
 4   Turnover_value       3555 non-null   object
 5   Trades               3555 non-null   object
 6   Clean_price_avg_%    3555 non-null   object
 7   Clean_price_open_%   3555 non-null   object
 8   Clean_price_high_%   3555 non-null   object
 9   Clean_price_low_%    3555 non-null   object
 10  Clean_price_close_%  3555 non-null   object
 11  Change_%             3555 non-null   object
dtypes: object(12)
memory usage: 361.1+ KB

In [269]:
# fill null obs with zero

df_bonds.fillna(0, inplace = True)

<ipython-input-269-f12ad0f1699d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bonds.fillna(0, inplace = True)

In [270]:
df_bonds

,Symbol,Company_name,Market,Volumne,Turnover_value,Trades,Clean_price_avg_%,Clean_price_open_%,Clean_price_high_%,Clean_price_low_%,Clean_price_close_%,Change_%
15,IMP26E,IMPACT DEVELOPER & CONTRACTOR 2026 EUR,TOTAL,48,122967.62,8,102.8,102,103.14,102,103.14,1.02
17,PBK28E,Patria Bank Obligatiuni 2028 EUR,TOTAL,5,13147.74,1,104.1,104.1,104.1,104.1,104.1,0.34
19,BRK26,SSIF BRK FINANCIAL GROUP - Ob. 2026,TOTAL,95,9552.4,6,98.9,99.28,99.28,98.81,98.81,-0.47
26,R2210A,MINISTERUL FINANTELOR,TOTAL,12,1206.24,3,99.42,99.4399,99.4399,99.4,99.4,0.71
27,R2212A,0,TOTAL,103,10298.97,2,99.4,99.4,99.4,99.4,99.4,0
...,...,...,...,...,...,...,...,...,...,...,...,...
28945,R2406AE,MINISTERUL FINANTELOR - EURO,TOTAL,14,6881.28,2,98.5011,98.5011,98.5011,98.5011,98.5011,-0.74
28947,R2312A,MINISTERUL FINANTELOR PUBLICE,TOTAL,920,94299.58,14,99.3995,99.4,99.4699,99.38,99.4699,0
28948,R2408A,0,TOTAL,369,36333.82,10,98.0755,98,98.3788,98,98.3788,0.39
28949,R2508AE,0,TOTAL,61,28865.64,3,95.1518,95,95.2988,95,95.2987,0.74
28950,R2512AE,0,TOTAL,16806,7882040.1,23,93.0444,93,93.25,93,93,0.08

In [271]:
# drop row with index 16 beacuse we don't need it
df_bonds = df_bonds.drop(df_bonds.index[16])

In [272]:
# reset index on df

df_bonds.reset_index(drop = True, inplace = True)

In order to assign the date on every obs, in cronological order, from each file extracted, I will create a new column named ['Groups'] in which I will divide the bonds into two groups: corporate bonds and institutional bonds

In [273]:
# Define a function to assign group id's based on the starting letter
def assign_id(name):
    if str(name).startswith('R2'):
        return 'IB'
    else:
        return 'CB'

# Apply the function to the DataFrame column
df_bonds['ID'] = df_bonds['Symbol'].apply(assign_id)
df_bonds

,Symbol,Company_name,Market,Volumne,Turnover_value,Trades,Clean_price_avg_%,Clean_price_open_%,Clean_price_high_%,Clean_price_low_%,Clean_price_close_%,Change_%,ID
0,IMP26E,IMPACT DEVELOPER & CONTRACTOR 2026 EUR,TOTAL,48,122967.62,8,102.8,102,103.14,102,103.14,1.02,CB
1,PBK28E,Patria Bank Obligatiuni 2028 EUR,TOTAL,5,13147.74,1,104.1,104.1,104.1,104.1,104.1,0.34,CB
2,BRK26,SSIF BRK FINANCIAL GROUP - Ob. 2026,TOTAL,95,9552.4,6,98.9,99.28,99.28,98.81,98.81,-0.47,CB
3,R2210A,MINISTERUL FINANTELOR,TOTAL,12,1206.24,3,99.42,99.4399,99.4399,99.4,99.4,0.71,IB
4,R2212A,0,TOTAL,103,10298.97,2,99.4,99.4,99.4,99.4,99.4,0,IB
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3549,R2406AE,MINISTERUL FINANTELOR - EURO,TOTAL,14,6881.28,2,98.5011,98.5011,98.5011,98.5011,98.5011,-0.74,IB
3550,R2312A,MINISTERUL FINANTELOR PUBLICE,TOTAL,920,94299.58,14,99.3995,99.4,99.4699,99.38,99.4699,0,IB
3551,R2408A,0,TOTAL,369,36333.82,10,98.0755,98,98.3788,98,98.3788,0.39,IB
3552,R2508AE,0,TOTAL,61,28865.64,3,95.1518,95,95.2988,95,95.2987,0.74,IB
3553,R2512AE,0,TOTAL,16806,7882040.1,23,93.0444,93,93.25,93,93,0.08,IB

In [274]:
# create a date column and assign the same date to all observations in a group. The date will increase by one for every group.

# Create a new column `Group` in `df` to store the group labels
df_bonds['Group'] = ''

# Create a dictionary to map the group labels to the corresponding rows in `df`
group_map = {}

# Iterate over the rows of `df` and assign the group label to the `Group` column and the group map
for i in range(len(df_bonds)):
    if df_bonds.loc[i, 'ID'] == 'CB':
      if i > 0 and df_bonds.loc[i-1, 'ID'] == 'CB':
        df_bonds.loc[i, 'Group'] = df_bonds.loc[i - 1, 'Group']
      else:
        group_label = str(len(group_map)+1)
        df_bonds.loc[i, 'Group'] = group_label
        group_map[group_label] = [i]
    elif df_bonds.loc[i, 'ID'] == 'IB':
        if df_bonds.loc[i - 1, 'ID'] == 'CB':
            group_label = df_bonds.loc[i - 1, 'Group']
            df_bonds.loc[i, 'Group'] = group_label
            group_map[group_label] = [i]
        else:
            group_label = df_bonds.loc[i - 1, 'Group']
            df_bonds.loc[i, 'Group'] = group_label
            group_map[group_label].append(i)

# Create a new column 'Date' with assigned dates
date_dict = {}
current_date = pd.Timestamp('2023-01-01')

df_bonds['Date'] = df_bonds['Group'].apply(lambda x: date_dict.setdefault(x, current_date + pd.DateOffset(days=len(date_dict))))
# Print the new DataFrame `data1`
df_bonds

,Symbol,Company_name,Market,Volumne,Turnover_value,Trades,Clean_price_avg_%,Clean_price_open_%,Clean_price_high_%,Clean_price_low_%,Clean_price_close_%,Change_%,ID,Group,Date
0,IMP26E,IMPACT DEVELOPER & CONTRACTOR 2026 EUR,TOTAL,48,122967.62,8,102.8,102,103.14,102,103.14,1.02,CB,1,2023-01-01
1,PBK28E,Patria Bank Obligatiuni 2028 EUR,TOTAL,5,13147.74,1,104.1,104.1,104.1,104.1,104.1,0.34,CB,1,2023-01-01
2,BRK26,SSIF BRK FINANCIAL GROUP - Ob. 2026,TOTAL,95,9552.4,6,98.9,99.28,99.28,98.81,98.81,-0.47,CB,1,2023-01-01
3,R2210A,MINISTERUL FINANTELOR,TOTAL,12,1206.24,3,99.42,99.4399,99.4399,99.4,99.4,0.71,IB,1,2023-01-01
4,R2212A,0,TOTAL,103,10298.97,2,99.4,99.4,99.4,99.4,99.4,0,IB,1,2023-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3549,R2406AE,MINISTERUL FINANTELOR - EURO,TOTAL,14,6881.28,2,98.5011,98.5011,98.5011,98.5011,98.5011,-0.74,IB,147,2023-05-27
3550,R2312A,MINISTERUL FINANTELOR PUBLICE,TOTAL,920,94299.58,14,99.3995,99.4,99.4699,99.38,99.4699,0,IB,147,2023-05-27
3551,R2408A,0,TOTAL,369,36333.82,10,98.0755,98,98.3788,98,98.3788,0.39,IB,147,2023-05-27
3552,R2508AE,0,TOTAL,61,28865.64,3,95.1518,95,95.2988,95,95.2987,0.74,IB,147,2023-05-27
3553,R2512AE,0,TOTAL,16806,7882040.1,23,93.0444,93,93.25,93,93,0.08,IB,147,2023-05-27

In [275]:
# drop "Market" column on df, because we do not need it any more

df_bonds = df_bonds.drop('Market', axis = 1)

In [276]:
df_bonds.columns

Index(['Symbol', 'Company_name', 'Volumne', 'Turnover_value', 'Trades',
       'Clean_price_avg_%', 'Clean_price_open_%', 'Clean_price_high_%',
       'Clean_price_low_%', 'Clean_price_close_%', 'Change_%', 'ID', 'Group',
       'Date'],
      dtype='object')

In [277]:
# Convert specified columns from object into float or integer in df

float_columns = ['Clean_price_avg_%', 'Clean_price_open_%','Clean_price_high_%', 'Clean_price_low_%', 'Clean_price_close_%', 'Change_%', 'Turnover_value']
int_columns = ['Volumne','Trades']
# Convert all specified columns to float
df_bonds[float_columns] = df_bonds[float_columns].astype(float)
# Convert all specified columns to integer
df_bonds[int_columns] = df_bonds[int_columns].astype(int)

In [278]:
# summary info of df
df_bonds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3554 entries, 0 to 3553
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Symbol               3554 non-null   object
 1   Company_name         3554 non-null   object
 2   Volumne              3554 non-null   int64
 3   Turnover_value       3554 non-null   float64
 4   Trades               3554 non-null   int64
 5   Clean_price_avg_%    3554 non-null   float64
 6   Clean_price_open_%   3554 non-null   float64
 7   Clean_price_high_%   3554 non-null   float64
 8   Clean_price_low_%    3554 non-null   float64
 9   Clean_price_close_%  3554 non-null   float64
 10  Change_%             3554 non-null   float64
 11  ID                   3554 non-null   object
 12  Group                3554 non-null   object
 13  Date                 3554 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(7), int64(2), object(4)
memory usage: 388.8+ KB

In [279]:
# save df to csv file

file_path = 'drive/MyDrive/Colab Notebooks/BVB_project/BVB_bonds.csv'

df_bonds.to_csv(file_path, index = False)

## Df Funds

In [280]:
# view summary info on df
df_funds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4095 entries, 0 to 4094
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   0 non-null      float64
 1   Unnamed: 1   1593 non-null   object
 2   Unnamed: 2   1281 non-null   object
 3   Unnamed: 3   889 non-null    object
 4   Unnamed: 4   590 non-null    object
 5   Unnamed: 5   889 non-null    object
 6   Unnamed: 6   889 non-null    object
 7   Unnamed: 7   889 non-null    object
 8   Unnamed: 8   889 non-null    object
 9   Unnamed: 9   889 non-null    object
 10  Unnamed: 10  889 non-null    object
 11  Unnamed: 11  1181 non-null   object
 12  Unnamed: 12  1181 non-null   object
 13  Unnamed: 13  1181 non-null   object
 14  Unnamed: 14  590 non-null    object
 15  Unnamed: 15  590 non-null    object
dtypes: float64(1), object(15)
memory usage: 512.0+ KB

In [281]:
# quick view on df
df_funds

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,EMISE DE ENTITATI DIN ROMANIA / DOMESTIC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4090,NaN,Pretul de inchidere din piata principala a rez...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4092,NaN,Simbol / Symbol,Denumire societate / Company name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4093,NaN,PTENGETF,FONDUL DESCHIS DE INVESTITII ETF ENERGIE PATRI...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4094,NaN,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [282]:
# drop null obs on df

df_funds = df_funds.dropna(how = 'all')

In [283]:
# drop "Unnamed: 0" column on df, because it has only null obs

df_funds = df_funds.drop('Unnamed: 0', axis = 1)

In [284]:
# rename the columns in df

columns_renamed = ['Symbol', 'Company_name','Market', 'Face_value', 'Close ','Change_%', 'Open', 'High', 'Low','Avg_price', 'Volume', 'Turnover','No_of_trades', '52_High', '52_Min']

df_funds.columns = columns_renamed
df_funds.rename_axis('Index')

,Symbol,Company_name,Market,Face_value,Close,Change_%,Open,High,Low,Avg_price,Volume,Turnover,No_of_trades,52_High,52_Min
Index,,,,,,,,,,,,,,,
2,EMISE DE ENTITATI DIN ROMANIA / DOMESTIC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Unitati de fond / Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Simbol / Symbol,Denumire societate / Company name,Sectiune piata / Market,VN / Face value,Inch./ Close,Var / Change (%),Desc. / Open,Max. / High,Min. / Low,Pr.med. / Avg.,Nr.actiuni / Volume,Val. totala / Turnover,Nr.trz. / No. of trades,52 Max / 52 High,52 Min / 52 Min
11,NaN,TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
13,OPCVM tranzactionabile / Exchange Traded Fund...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4088,NaN,TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31940,596562.471,497,NaN,NaN
4090,Pretul de inchidere din piata principala a rez...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4092,Simbol / Symbol,Denumire societate / Company name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4093,PTENGETF,FONDUL DESCHIS DE INVESTITII ETF ENERGIE PATRI...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4094,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [285]:
# drop rows on df

rows_to_drop_df_funds = ['TITLURI DE CREDIT / DEBT SECURITIES', 'EMISE DE ENTITATI DIN ROMANIA / DOMESTIC','Unitati de fond / Units', 'OPCVM tranzactionabile /  Exchange Traded Funds (ETF)',
                         'Regular', 'Deal','Denumire emitent', 'Company name', 'Denumire societate / Company name', ' Simbol / Symbol ', 'Denumire societate Company name',
                         'Pretul de inchidere din piata principala a rezultat dintr-o tranzactie cross pentru urmatoarele simboluri / The closing price in the main market was given by a cross trade for the following symbols: ']

df_funds = df_funds[~df_funds['Symbol'].isin(rows_to_drop_df_funds)]
df_funds = df_funds[~df_funds['Company_name'].isin(rows_to_drop_df_funds)]
df_funds = df_funds[~df_funds['Market'].isin(rows_to_drop_df_funds)]

In [286]:
# drop rows with "TOTLAL" obs on "Company_name" from df

rows_to_drop = ['TOTAL']
df_funds = df_funds[~df_funds['Company_name'].isin(rows_to_drop)]

In [287]:
# drop "Market" column on df, because we do not need it any more

df_funds = df_funds.drop('Market', axis = 1)

In [288]:
# fill null obs with 0 on df
df_funds.fillna(0, inplace = True)

In [289]:
# drop rows where column "Avg_price" has 0 values

df_funds = df_funds[df_funds['Avg_price'] != 0]

In [290]:
# reset index on df

df_funds.reset_index(drop = True, inplace = True)

In [291]:
df_funds

,Symbol,Company_name,Face_value,Close,Change_%,Open,High,Low,Avg_price,Volume,Turnover,No_of_trades,52_High,52_Min
0,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,18.680,-0.23,18.850,18.898,18.650,18.7727,12134,227787.996,149,18.946,13.830
1,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,18.400,0.69,18.250,18.440,18.250,18.3270,6348,116339.824,149,18.946,15.428
2,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,17.344,0.00,17.450,17.630,17.344,17.3923,3518,61186.400,51,18.946,15.640
3,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,17.420,0.81,17.432,17.450,17.300,17.4057,4018,69936.152,47,18.946,15.640
4,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,17.600,1.85,17.300,17.600,17.300,17.4493,3260,56885.000,75,18.946,15.640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,PTENGETF,FONDUL DESCHIS DE INVESTITII ETF ENERGIE PATRI...,5,5.659,0.71,5.630,5.661,5.630,5.6435,2078,11727.303,29,5.659,4.903
294,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,20.930,-0.10,20.740,20.930,20.740,20.8088,12751,265333.885,253,20.930,15.860
295,PTENGETF,FONDUL DESCHIS DE INVESTITII ETF ENERGIE PATRI...,5,5.697,0.67,5.669,5.697,5.660,5.6713,9519,53985.881,42,5.697,4.903
296,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,20.950,-0.19,20.930,20.950,20.920,20.9441,27187,569407.815,444,20.950,15.860
297,PTENGETF,FONDUL DESCHIS DE INVESTITII ETF ENERGIE PATRI...,5,5.715,0.32,5.700,5.730,5.700,5.7131,4753,27154.656,53,5.715,4.903

In [292]:
# view summary info on df

df_funds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 298 entries, 0 to 297
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Symbol        298 non-null    object
 1   Company_name  298 non-null    object
 2   Face_value    298 non-null    int64
 3   Close         298 non-null    float64
 4   Change_%      298 non-null    float64
 5   Open          298 non-null    float64
 6   High          298 non-null    float64
 7   Low           298 non-null    float64
 8   Avg_price     298 non-null    float64
 9   Volume        298 non-null    int64
 10  Turnover      298 non-null    float64
 11  No_of_trades  298 non-null    int64
 12  52_High       298 non-null    float64
 13  52_Min        298 non-null    float64
dtypes: float64(9), int64(3), object(2)
memory usage: 32.7+ KB

In [293]:
# create a date column and assign the same date to all observations in a range from the first observation to the moment when the observation is repeated in the dataframe.

current_date = None
date_counter = 0

# Initialize a list to store the new dates
new_dates = []

# Iterate through the DataFrame
for index, row in df_funds.iterrows():
    name = row['Symbol']

    if name == 'TVBETETF' or current_date is None:
        # If the name is 'Alice' or current_date is None, assign the current date
        if current_date is None:
            current_date = pd.Timestamp('2023-01-01')
        else:
            current_date += pd.DateOffset(days=1)


    new_dates.append(current_date)

# Create a new column with the calculated dates
df_funds['Date'] = new_dates

# Display the DataFrame with the new column
df_funds

,Symbol,Company_name,Face_value,Close,Change_%,Open,High,Low,Avg_price,Volume,Turnover,No_of_trades,52_High,52_Min,Date
0,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,18.680,-0.23,18.850,18.898,18.650,18.7727,12134,227787.996,149,18.946,13.830,2023-01-01
1,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,18.400,0.69,18.250,18.440,18.250,18.3270,6348,116339.824,149,18.946,15.428,2023-01-02
2,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,17.344,0.00,17.450,17.630,17.344,17.3923,3518,61186.400,51,18.946,15.640,2023-01-03
3,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,17.420,0.81,17.432,17.450,17.300,17.4057,4018,69936.152,47,18.946,15.640,2023-01-04
4,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,17.600,1.85,17.300,17.600,17.300,17.4493,3260,56885.000,75,18.946,15.640,2023-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,PTENGETF,FONDUL DESCHIS DE INVESTITII ETF ENERGIE PATRI...,5,5.659,0.71,5.630,5.661,5.630,5.6435,2078,11727.303,29,5.659,4.903,2023-05-24
294,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,20.930,-0.10,20.740,20.930,20.740,20.8088,12751,265333.885,253,20.930,15.860,2023-05-25
295,PTENGETF,FONDUL DESCHIS DE INVESTITII ETF ENERGIE PATRI...,5,5.697,0.67,5.669,5.697,5.660,5.6713,9519,53985.881,42,5.697,4.903,2023-05-25
296,TVBETETF,FONDUL DESCHIS DE INVESTITII ETF BET PATRIA-TR...,5,20.950,-0.19,20.930,20.950,20.920,20.9441,27187,569407.815,444,20.950,15.860,2023-05-26
297,PTENGETF,FONDUL DESCHIS DE INVESTITII ETF ENERGIE PATRI...,5,5.715,0.32,5.700,5.730,5.700,5.7131,4753,27154.656,53,5.715,4.903,2023-05-26

In [294]:
# save df to csv file

file_path = 'drive/MyDrive/Colab Notebooks/BVB_project/BVB_funds.csv'
df_funds.to_csv(file_path, index = False)

## DF Structured

In [295]:
df_structured.head(3)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Produse structurate / Structured,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [296]:
# drop rows with null obs on df

df_structured.dropna(how = 'all', inplace = True)

In [297]:
# drop column "Unnamed: 0" beacuse has only null obs

df_structured = df_structured.drop('Unnamed: 0', axis = 1)

In [298]:
# rename columns on df

column_names = ['Symbol', 'Inst_name', 'Market', 'Close', 'Change_%', 'Open', 'High', 'Low', 'Avg_price', 'Volumne', 'Turnover', 'Trades', '52_High', '52_min']

df_structured.columns = column_names
df_structured.rename_axis('Index')

,Symbol,Inst_name,Market,Close,Change_%,Open,High,Low,Avg_price,Volumne,Turnover,Trades,52_High,52_min
Index,,,,,,,,,,,,,,
2,Produse structurate / Structured,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Certificate / Certificates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Simbol / Symbol,Denumire instrument / Instrument name,Sectiune piata / Market,Inch./ Close,Var / Change (%),Desc./ Open,Max. / High,Min. / Low,Pr.med. / Avg.,Nr.instrumente / Volume,Val. totala / Turnover,Nr.trz. / No. of trades,52 Max / 52 High,52 Min / 52 Min
8,EBADSTL7,ADIDAS TURBO LONG 0.10/215/225,Regular STR,10.7,-18.13,10.7,10.7,10.7,10.7,40,428,1,49.25,6.5
9,BKSLVTL1,BRK Argint Turbo Long 19.5,Regular STR,0.62,-12.68,0.68,0.68,0.59,0.6,297586,178726.35,23,1.99,0.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11798,RCFP23L1,Call Warrant on Fondul Proprietatea SA,Regular STR,0.85,4.94,0.85,0.86,0.82,0.84,170450,143330,45,2.95,0.66
11799,RCSNP23L1,Call Warrant on OMV Petrom SA,Regular STR,14.04,10.73,13.3,14.04,13.3,13.56,130,1763.42,3,14.04,3.96
11800,RCONE24F1,Call Warrant on One United Properties SA,Regular STR,0.03,0,0.03,0.03,0.03,0.03,40000,1200,2,0.13,0.025
11801,RCSNG23L1,Call Warrant on Societatea Nationala de Gaze N...,Regular STR,4.78,24.16,4.72,4.78,4.72,4.73,2100,9938,5,8.67,2.33
11803,NaN,TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,433081,168022.668,71,NaN,NaN

In [299]:
# drop rows on df

rows_to_drop_df_struct= ['Produse structurate / Structured']

df_structured = df_structured[~df_structured['Symbol'].isin(rows_to_drop_df_struct)]

In [300]:
# create a date column and assign the same date to all observations in a range from the first observation to the moment when the observation is repeated in the dataframe.

current_date = None
date_counter = 0

# Initialize a list to store the new dates
new_dates = []

# Iterate through the DataFrame
for index, row in df_structured.iterrows():
    name = row['Symbol']

    if name == 'Certificate / Certificates' or current_date is None:
        # If the name is 'Alice' or current_date is None, assign the current date
        if current_date is None:
            current_date = pd.Timestamp('2023-01-01')
        else:
            current_date += pd.DateOffset(days=1)


    new_dates.append(current_date)

# Create a new column with the calculated dates
df_structured['Date'] = new_dates

# Display the DataFrame with the new column
df_structured

,Symbol,Inst_name,Market,Close,Change_%,Open,High,Low,Avg_price,Volumne,Turnover,Trades,52_High,52_min,Date
4,Certificate / Certificates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-01
7,Simbol / Symbol,Denumire instrument / Instrument name,Sectiune piata / Market,Inch./ Close,Var / Change (%),Desc./ Open,Max. / High,Min. / Low,Pr.med. / Avg.,Nr.instrumente / Volume,Val. totala / Turnover,Nr.trz. / No. of trades,52 Max / 52 High,52 Min / 52 Min,2023-01-01
8,EBADSTL7,ADIDAS TURBO LONG 0.10/215/225,Regular STR,10.7,-18.13,10.7,10.7,10.7,10.7,40,428,1,49.25,6.5,2023-01-01
9,BKSLVTL1,BRK Argint Turbo Long 19.5,Regular STR,0.62,-12.68,0.68,0.68,0.59,0.6,297586,178726.35,23,1.99,0.47,2023-01-01
10,BKAURTL11,BRK Aur Turbo Long 1620,Regular STR,1.39,-9.15,1.53,1.53,1.39,1.45,14070,20398.6,10,2.45,0.65,2023-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11798,RCFP23L1,Call Warrant on Fondul Proprietatea SA,Regular STR,0.85,4.94,0.85,0.86,0.82,0.84,170450,143330,45,2.95,0.66,2023-05-26
11799,RCSNP23L1,Call Warrant on OMV Petrom SA,Regular STR,14.04,10.73,13.3,14.04,13.3,13.56,130,1763.42,3,14.04,3.96,2023-05-26
11800,RCONE24F1,Call Warrant on One United Properties SA,Regular STR,0.03,0,0.03,0.03,0.03,0.03,40000,1200,2,0.13,0.025,2023-05-26
11801,RCSNG23L1,Call Warrant on Societatea Nationala de Gaze N...,Regular STR,4.78,24.16,4.72,4.78,4.72,4.73,2100,9938,5,8.67,2.33,2023-05-26
11803,NaN,TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,433081,168022.668,71,NaN,NaN,2023-05-26

In [301]:
# drop rows on df

rows_to_drop_df_structured= ['Certificate / Certificates','Simbol / Symbol', 'Warrants', 'TOTAL']

df_structured = df_structured[~df_structured['Symbol'].isin(rows_to_drop_df_structured)]
df_structured = df_structured[~df_structured['Inst_name'].isin(rows_to_drop_df_structured)]
#df_funds = df_funds[~df_funds['Market'].isin(rows_to_drop_df_funds)]

In [302]:
df_structured

,Symbol,Inst_name,Market,Close,Change_%,Open,High,Low,Avg_price,Volumne,Turnover,Trades,52_High,52_min,Date
8,EBADSTL7,ADIDAS TURBO LONG 0.10/215/225,Regular STR,10.7,-18.13,10.7,10.7,10.7,10.7,40,428,1,49.25,6.5,2023-01-01
9,BKSLVTL1,BRK Argint Turbo Long 19.5,Regular STR,0.62,-12.68,0.68,0.68,0.59,0.6,297586,178726.35,23,1.99,0.47,2023-01-01
10,BKAURTL11,BRK Aur Turbo Long 1620,Regular STR,1.39,-9.15,1.53,1.53,1.39,1.45,14070,20398.6,10,2.45,0.65,2023-01-01
11,BKAURTL13,BRK Aur Turbo Long 1675,Regular STR,4.97,-12.5,5.46,5.49,4.97,5.38,759,4081.96,8,10.47,2.58,2023-01-01
12,BKAURTS13,BRK Aur Turbo Short 1880,Regular STR,0.83,7.79,0.83,0.83,0.83,0.83,200,166,1,1.38,0.27,2023-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11797,RCBRD23L1,Call Warrant on BRD Groupe Societe Generale SA,Regular STR,0.054,17.39,0.048,0.054,0.048,0.049,206751,10194.548,9,0.45,0.03,2023-05-26
11798,RCFP23L1,Call Warrant on Fondul Proprietatea SA,Regular STR,0.85,4.94,0.85,0.86,0.82,0.84,170450,143330,45,2.95,0.66,2023-05-26
11799,RCSNP23L1,Call Warrant on OMV Petrom SA,Regular STR,14.04,10.73,13.3,14.04,13.3,13.56,130,1763.42,3,14.04,3.96,2023-05-26
11800,RCONE24F1,Call Warrant on One United Properties SA,Regular STR,0.03,0,0.03,0.03,0.03,0.03,40000,1200,2,0.13,0.025,2023-05-26
11801,RCSNG23L1,Call Warrant on Societatea Nationala de Gaze N...,Regular STR,4.78,24.16,4.72,4.78,4.72,4.73,2100,9938,5,8.67,2.33,2023-05-26

In [303]:
# drop 'Market' column on df, beacuse we don't need it any more

df_structured = df_structured.drop('Market', axis = 1)

In [304]:
df_structured.fillna(0, inplace = True)

In [305]:
df_structured.reset_index(drop = True, inplace = True)

In [306]:
df_structured.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9322 entries, 0 to 9321
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Symbol     9322 non-null   object
 1   Inst_name  9322 non-null   object
 2   Close      9322 non-null   float64
 3   Change_%   9322 non-null   float64
 4   Open       9322 non-null   float64
 5   High       9322 non-null   float64
 6   Low        9322 non-null   float64
 7   Avg_price  9322 non-null   float64
 8   Volumne    9322 non-null   int64
 9   Turnover   9322 non-null   float64
 10  Trades     9322 non-null   int64
 11  52_High    9322 non-null   float64
 12  52_min     9322 non-null   float64
 13  Date       9322 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(9), int64(2), object(2)
memory usage: 1019.7+ KB

In [307]:
# save df_structured to csv file
file_path = 'drive/MyDrive/Colab Notebooks/BVB_project/BVB_structured.csv'
df_structured.to_csv(file_path, index= False)

#EDA

Now, I will do EDA (exploratory data analysis) on every DataFrame created (df_summary, df_equities, df_unlisted_shares, df_bonds, df_funds, df_futures, df_structured, df_other_inst), in order to clean it for analysis and for a better understanding